[WIP] Feature/fil streamz example
rapidsai/clx pull request #273
Opened 2020-10-23 19:16 UTC by brhodes10

2020-10-23 19:17 UTC, GPUtester commented
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

2020-10-26 19:38 UTC, brhodes10 commented
rerun tests

2020-10-26 19:46 UTC, BartleyR commented on examples/FIL_streamz_pipeline.ipynb
> +{
<p>I know you link to the data, but do you want to include how to download that data and get it into Kafka? Perhaps that outside the scope of this notebook though.</p><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/rapidsai/clx/pull/273/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='0'/>

2020-10-26 19:46 UTC, BartleyR commented on examples/FIL_streamz_pipeline.ipynb
> +{
<p>Aren't we publishing the model? </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/rapidsai/clx/pull/273/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='6'/>

2020-10-26 19:46 UTC, BartleyR commented on examples/FIL_streamz_pipeline.ipynb
> +{
<p>We need some more text about what this block of code is doing.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/rapidsai/clx/pull/273/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='19'/>

2020-10-26 19:46 UTC, BartleyR commented on examples/FIL_streamz_pipeline.ipynb
> +{
<p>Same here. Let's expand a bit on what we're doing with this function.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/rapidsai/clx/pull/273/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='20'/>

2020-10-26 19:46 UTC, BartleyR commented on examples/FIL_streamz_pipeline.ipynb
> +{
<p>Provide some text that summarizes what this function does.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/rapidsai/clx/pull/273/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='23'/>

2020-10-26 19:46 UTC, BartleyR commented on examples/FIL_streamz_pipeline.ipynb
> +{
<p>It's a good idea to include some conclusions here and possible ideas for how things can be expanded in the future.</p><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/rapidsai/clx/pull/273/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='25'/>

2020-11-03 22:38 UTC, raykallen requested changes
Can you add in the notebook outputs as examples?

2020-11-05 18:42 UTC, brhodes10 commented
rerun tests

2020-11-05 21:20 UTC, brhodes10 commented
> Can you add in the notebook outputs as examples?

Thanks ! Updated

2020-12-03 15:19 UTC, BartleyR approved these changes

2020-12-04 17:12 UTC, raykallen approved these changes

2020-12-04 17:22 UTC, merged