Create labeler.yml
rapidsai/clx pull request #318
Opened 2020-12-23 21:09 UTC by jolorunyomi

2021-01-05 15:45 UTC, ajschmidt8 approved these changes

2021-01-21 16:11 UTC, mike-wendt requested changes

2021-01-21 16:11 UTC, mike-wendt commented on .github/labeler.yml
> +  - 'java/**'
This section should match this repo's labels and the contents of the .github/CODEOWNERS file as a starting guide - PICs in this repo would then add or suggest more labels as needed

2021-01-21 16:11 UTC, mike-wendt commented on .github/labeler.yml
> +  - 'docker/**'
This should be removed

2021-01-25 20:47 UTC, ajschmidt8 requested changes

2021-01-25 20:47 UTC, ajschmidt8 commented on .github/labeler.yml
> +ci:
```suggestion
gpuCI:
```
there's no `ci` label, so this can probably be changed to `gpuCI`.

2021-01-27 22:33 UTC, ajschmidt8 approved these changes

2021-01-28 15:53 UTC, mike-wendt commented
@BartleyR any other labels based on content you would like us to add here? Please add your review when you can

2021-01-28 16:14 UTC, BartleyR requested changes
I think it'd be good to have an `integration` label that we could use to label things in the `siem_integrations` folder for now. We would also be able to use it to label future integrations. I went ahead and made the label for the repo.

2021-02-02 22:48 UTC, mike-wendt commented
> I think it'd be good to have an `integration` label that we could use to label things in the `siem_integrations` folder for now. We would also be able to use it to label future integrations. I went ahead and made the label for the repo.

@jolorunyomi can you add this to the config? thanks!

2021-02-04 04:23 UTC, mike-wendt approved these changes

2021-02-04 04:24 UTC, mike-wendt commented
@BartleyR I think we're ready for a review, thanks for the help

2021-02-04 18:30 UTC, BartleyR approved these changes

2021-02-17 19:08 UTC, mike-wendt commented
@gpucibot merge

2021-02-17 19:08 UTC, merged